# Generated by Django 4.2.2 on 2023-06-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=2550)),
                ('qualification', models.CharField(max_length=255)),
                ('tech_skills', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=255)),
                ('interests', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=2550)),
            ],
        ),
    ]
